import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <div className="w-full p-5 flex justify-center items-center">
            <Link className="text-white" href={"/"}>
              Home
            </Link>
          </div>
        </header>
        <section className="flex flex-col gap-2 items-center justify-center w-full h-full py-10">
          <div className="container max-w-5xl">{children}</div>
        </section>
      </body>
    </html>
  );
}
